'use strict';

// Pure rendering for the Meta CAPI admin dashboard note (no IO — testable).
// Consumed by scripts/capi-report.js, which reads the DB and writes the vault note.

const STATUS_EMOJI = { sent: '✅', failed: '❌', skipped: '⏭️' };

function statusEmoji(status) {
  return STATUS_EMOJI[status] || '❔';
}

// SQLite CURRENT_TIMESTAMP is UTC 'YYYY-MM-DD HH:MM:SS'. Parse it as UTC, not local.
function parseUtc(s) {
  if (!s) return null;
  const iso = String(s).includes('T') ? String(s) : String(s).replace(' ', 'T') + 'Z';
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? null : d;
}

function truncateMiddle(s, max = 20) {
  if (!s) return '—';
  if (s.length <= max) return s;
  return `${s.slice(0, 12)}…${s.slice(-4)}`;
}

function fmtUtc(date) {
  return date ? date.toISOString().replace('T', ' ').slice(0, 16) : '—';
}

function computeSummary(rows, now = Date.now()) {
  const counts = { sent: 0, failed: 0, skipped: 0 };
  let mostRecent = null;
  let last24h = 0;
  const dayAgo = now - 24 * 60 * 60 * 1000;

  for (const r of rows) {
    if (counts[r.status] !== undefined) counts[r.status] += 1;
    const d = parseUtc(r.created_at);
    if (d) {
      if (!mostRecent || d > mostRecent) mostRecent = d;
      if (d.getTime() >= dayAgo) last24h += 1;
    }
  }

  const attempted = counts.sent + counts.failed;
  const deliveryRate = attempted === 0 ? null : (counts.sent / attempted) * 100;

  return {
    total: rows.length,
    sent: counts.sent,
    failed: counts.failed,
    skipped: counts.skipped,
    deliveryRate,
    last24h,
    mostRecent,
  };
}

function renderReport(rows, now = Date.now(), recentLimit = 50) {
  const s = computeSummary(rows, now);
  const generatedIso = new Date(now).toISOString();
  const rate = s.deliveryRate === null ? '—' : `${s.deliveryRate.toFixed(1)}%`;

  const lines = [
    '---',
    'title: Meta CAPI Admin',
    `generated: ${generatedIso}`,
    'tags: [nsfm, admin, meta-capi]',
    '---',
    '',
    '# Meta CAPI — Purchase Events',
    '',
    '> [!info] Auto-generated by `npm run capi:report` — re-run to refresh. Do not edit by hand.',
    `> Last generated: ${generatedIso}`,
    '',
    '## Summary',
    '',
    '| Metric | Value |',
    '| --- | --- |',
    `| Total events | ${s.total} |`,
    `| ✅ Sent | ${s.sent} |`,
    `| ❌ Failed | ${s.failed} |`,
    `| ⏭️ Skipped | ${s.skipped} |`,
    `| Delivery rate | ${rate} |`,
    `| Last 24h | ${s.last24h} |`,
    `| Most recent | ${s.mostRecent ? fmtUtc(s.mostRecent) + ' UTC' : '—'} |`,
    '',
    `## Recent events (last ${recentLimit})`,
    '',
  ];

  if (rows.length === 0) {
    lines.push('_No events recorded yet._', '');
    return lines.join('\n');
  }

  const recentRows = [...rows].sort((a, b) => (b.id || 0) - (a.id || 0)).slice(0, recentLimit);

  lines.push('| # | Time (UTC) | Status | HTTP | Session | Trace / Error |');
  lines.push('| --- | --- | --- | --- | --- | --- |');
  for (const r of recentRows) {
    const time = fmtUtc(parseUtc(r.created_at));
    const status = `${statusEmoji(r.status)} ${r.status || '—'}`;
    const http = r.http_status ?? '—';
    const session = truncateMiddle(r.stripe_session_id);
    let detail = '—';
    if (r.status === 'failed' && r.error) detail = String(r.error).slice(0, 40);
    else if (r.fb_trace_id) detail = String(r.fb_trace_id);
    detail = detail.replace(/\|/g, '\\|'); // don't break the markdown table
    lines.push(`| ${r.id ?? '—'} | ${time} | ${status} | ${http} | ${session} | ${detail} |`);
  }
  lines.push('');
  return lines.join('\n');
}

module.exports = { statusEmoji, parseUtc, truncateMiddle, computeSummary, renderReport };
